version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    ports:
      - "5432:5432"

  run_migrations:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  api:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
      DEBUG: 'False'
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./skymarket/config:/opt/app/config
      - ./skymarket/users:/opt/app/users
      - ./skymarket/ads:/opt/app/ads
      - ./skymarket/redoc:/opt/app/redoc

  frontend:
    build: ./frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "3000:3000"
    volumes:
      - ./skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ./skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  frontend:
